version: "3.9"

services:
  brokerage:
    build: .
    container_name: brokerage-service
    ports:
      - "8080:8080"
    environment:
      # İstiyorsan profil kullanabilirsin, yoksa silebilirsin
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped